package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Almanac</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:650px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.2rem;color:var(--cream)}.entry{background:var(--bg2);border:1px solid var(--bg3);margin-bottom:.5rem;padding:.7rem}.entry-date{font-size:.65rem;color:var(--cm);display:flex;justify-content:space-between}.entry-title{font-size:.85rem;font-weight:600;margin:.2rem 0}.entry-body{font-family:var(--serif);font-size:.82rem;color:var(--cd);line-height:1.8;white-space:pre-wrap}.entry-meta{font-size:.6rem;color:var(--cm);margin-top:.3rem;display:flex;gap:.5rem}.mood{font-size:.75rem}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:95%;max-width:600px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=date],textarea,select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}textarea{resize:vertical;min-height:150px;font-family:var(--serif);font-size:.85rem;line-height:1.8}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Almanac</span></h1><button class="btn btn-p" onclick="showNew()">+ Entry</button></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/almanac/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div class="overview" id="ov"></div><div id="list"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function init(){const sd=await api('/api/stats');
document.getElementById('ov').innerHTML='<div class="stat"><b>'+sd.entries+'</b>Entries</div><div class="stat"><b>'+sd.words.toLocaleString()+'</b>Words</div><div class="stat"><b style="color:var(--gold)">'+sd.streak+'</b>Day Streak</div><div class="stat"><b>'+sd.months+'</b>Months</div>';load()}
async function load(){const d=await api('/api/entries');const entries=d.entries||[];
document.getElementById('list').innerHTML=entries.length?entries.map(e=>'<div class="entry"><div class="entry-date"><span>'+e.date+'</span>'+(e.mood?'<span class="mood">'+esc(e.mood)+'</span>':'')+'</div>'+(e.title?'<div class="entry-title">'+esc(e.title)+'</div>':'')+'<div class="entry-body">'+esc(e.body)+'</div><div class="entry-meta"><span>'+e.word_count+' words</span>'+(e.tags?'<span>'+esc(e.tags)+'</span>':'')+'<span style="cursor:pointer;color:var(--cm)" onclick="del(\''+e.id+'\')">del</span></div></div>').join(''):'<div class="empty">No journal entries yet. Start writing today.</div>'}
async function del(id){if(!confirm('Delete entry?'))return;await api('/api/entries/'+id,{method:'DELETE'});load();init()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Entry</h2><label class="fl">Date</label><input type="date" id="ne-date" value="'+new Date().toISOString().split('T')[0]+'"><label class="fl">Title (optional)</label><input type="text" id="ne-title"><label class="fl">How are you feeling?</label><select id="ne-mood" style="width:auto"><option value="">-</option><option>😊</option><option>😐</option><option>😔</option><option>🔥</option><option>💪</option><option>😴</option><option>🎉</option></select><label class="fl">Write</label><textarea id="ne-body" rows="8" placeholder="What happened today..."></textarea><label class="fl">Tags</label><input type="text" id="ne-tags" placeholder="work, personal"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Save</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={date:document.getElementById('ne-date').value,title:document.getElementById('ne-title').value,body:document.getElementById('ne-body').value,mood:document.getElementById('ne-mood').value,tags:document.getElementById('ne-tags').value};if(!b.body){alert('Write something!');return};await api('/api/entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load();init()}
function closeModal(){document.getElementById('modal').innerHTML=''}
init()
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
